//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDSync.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RDSync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   音声用フォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioFolder {
            get {
                return ResourceManager.GetString("AudioFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声ファイル保存先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialogLblAudioMedia {
            get {
                return ResourceManager.GetString("ConfigDialogLblAudioMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   写真ファイル保存先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialogLblImageMedia {
            get {
                return ResourceManager.GetString("ConfigDialogLblImageMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビデオファイル保存先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialogLblVideoMedia {
            get {
                return ResourceManager.GetString("ConfigDialogLblVideoMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder|. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialogOpenFIleFilter {
            get {
                return ResourceManager.GetString("ConfigDialogOpenFIleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialogText {
            get {
                return ResourceManager.GetString("ConfigDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。\n{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} / {1} のファイルコピーが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileCountMessage {
            get {
                return ResourceManager.GetString("FileCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}ファイルを処理しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileCountMessageEnd {
            get {
                return ResourceManager.GetString("FileCountMessageEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}({1}MB)を処理しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNameMessage {
            get {
                return ResourceManager.GetString("FileNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理を停止しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNameMessageCancel {
            get {
                return ResourceManager.GetString("FileNameMessageCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}でエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNameMessageError {
            get {
                return ResourceManager.GetString("FileNameMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理を停止する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Form1BtnCancel {
            get {
                return ResourceManager.GetString("Form1BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモリーカードからメディアファイルをコピーする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Form1BtnTransferText {
            get {
                return ResourceManager.GetString("Form1BtnTransferText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル(&amp;F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Form1MenuFile {
            get {
                return ResourceManager.GetString("Form1MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定(&amp;O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Form1MenuFileOption {
            get {
                return ResourceManager.GetString("Form1MenuFileOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(&amp;X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Form1MenuFileQuit {
            get {
                return ResourceManager.GetString("Form1MenuFileQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RDSync に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Form1Text {
            get {
                return ResourceManager.GetString("Form1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   写真用フォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageFolder {
            get {
                return ResourceManager.GetString("ImageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}MB / {1}MB ({2}%)の処理が完了しました。 (終了まで残り{3}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressMessage {
            get {
                return ResourceManager.GetString("ProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}MB処理をしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressMessageEnd {
            get {
                return ResourceManager.GetString("ProgressMessageEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon RDS {
            get {
                object obj = ResourceManager.GetObject("RDS", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   残り{3}日{2}時間{1}分{0}秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemainTimeDay {
            get {
                return ResourceManager.GetString("RemainTimeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残り{2}時間{1}分{0}秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemainTimeHour {
            get {
                return ResourceManager.GetString("RemainTimeHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残り{1}分{0}秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemainTimeMinute {
            get {
                return ResourceManager.GetString("RemainTimeMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残り{0}秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemainTimeSecond {
            get {
                return ResourceManager.GetString("RemainTimeSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビデオ用フォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VideoFolder {
            get {
                return ResourceManager.GetString("VideoFolder", resourceCulture);
            }
        }
    }
}
